/*

 SHURIKEN.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char shuriken[] =
{
  0x02,0x02,0xF6,0x84,0x42,0x7C,0x02,0x3C,
  0x40,0x3C,0x42,0x3E,0x6F,0x21,0x40,0x40,
  0x10,0x10,0x18,0x08,0x24,0x18,0x43,0x7D,
  0xC2,0xBE,0x24,0x18,0x18,0x10,0x08,0x08
};

/* End of SHURIKEN.C */
